### ISSUE TITLE
Add support for a `crud` permission.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-roles#11]
`crud` should be shorthand for `create`, `read`, `update`, `destroy`. This is different than `manage`, because `manage` includes _any_ action (e.g. `approve`, etc.), vs. just standard CRUD workflow stuff.

**Comment by andrewculver** [comment]
Perhaps there would be some receptiveness to implementing this upstream, but it has more utility locally. In regular CanCanCan, you'd just `can [:create, :read, :update, :destroy]`. For us, that translates into a longer list, e.g.:

```yaml
    SomeModel:
      - create
      - read
      - update
      - destroy
```

It would be nice to be able to:

```yaml
    SomeModel: crud
```

**Comment by scottharvey** [comment]
It looks like this has already been completed.

https://github.com/bullet-train-co/bullet_train-roles/blob/main/lib/models/role.rb#L153

**Comment by andrewculver** [comment]
@scottharvey Thanks for pointing this out!
